version: '3.9'

services:
  frontend:
    build:
      context: ./challenge_front
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    depends_on:
      - backend

  backend:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"